name: CSV to XML for mtd texts

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3
       - name: Set up JDK 1.8
         uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '17'
       - name: Clone project-doc with Ant
         run: ant -noinput -buildfile clone-projectDoc.xml

       - name: run xslt with jave in command lines
         run: java -jar ./project-documentation/editorialStylesheets/pipelineTools/saxon9he.jar -it -xsl:./project-documentation/stylesheets/mdt_inscriptions/mdtText_start.xsl -o:./temporary/mdt_texts.xml

       - name: Updating the edited texts in the repository
         run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add temporary/
          git commit -m "CSV successfully made into xml"
          git push
