name: XML Splitting

on:
  workflow_run:
    workflows: ["CSV to XML for mtd texts"]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3
       - name: Set up JDK 1.8
         uses: actions/setup-java@v3
         with:
           java-version: 1.8
       - name: Clone project-doc with Ant
         run: ant -noinput -buildfile clone-projectDoc.xml
            
       - name: Split xml into several with Ant
         run: ant -noinput -buildfile build_to_xml.xml

       - name: Updating the edited texts in the repository
         run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add output/
          git commit -m "xml successfully made into several"
          git push
